import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Generated by FlutterFire CLI.
///
/// Run `flutterfire configure --project=<your-project-id>` to regenerate.
/// See https://firebase.google.com/docs/flutter/setup
class DefaultFirebaseOptions {
  static bool get isConfigured =>
      android.apiKey != 'YOUR_ANDROID_API_KEY' &&
      ios.apiKey != 'YOUR_IOS_API_KEY';

  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVXLBF6GUKFD68hzCrtz5M1LACurQ1tc',
    appId: '1:197881816844:android:df869efd6a7bdcaa688b29',
    messagingSenderId: '197881816844',
    projectId: 'beads-out-qmet',
    storageBucket: 'beads-out-qmet.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq_Jg6Dhbfs3tVsffE1lSGXcinng8_AUw',
    appId: '1:197881816844:ios:88716cd55eb58c30688b29',
    messagingSenderId: '197881816844',
    projectId: 'beads-out-qmet',
    storageBucket: 'beads-out-qmet.firebasestorage.app',
    iosBundleId: 'com.qmet.beadsout',
  );
}
